---
- hosts: all
  gather_facts: yes
  become: yes

  vars_files:
    - vars/main.yml

  tasks:
    # Install Rails.
    - name: Install rails dependencies.
      apt: "name={{ item }} state=present"
      with_items:
        - ruby
        - gcc
        - ruby-all-dev
        - zlib1g-dev
        - libsqlite3-dev

    - command: which rails
      register: rails_result
      changed_when: false
      failed_when: false

    - name: Install rails.
      shell: gem install rails --no-ri --no-rdoc
      when: rails_result.rc != 0

    - name: Bundle Install Gems
      shell: cd /vagrant/simpleapi; bundle install

    - name: Start rails application.
      shell: "cd /vagrant/simpleapi; rails s -b 0.0.0.0 &"